spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      platform: postgres
      mode: always
      spring:
        thymeleaf:
          prefix: classpath:/templates/
